SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `mitglieder` (
  `id` int(5) UNSIGNED NOT NULL,
  `username` varchar(255) CHARACTER SET utf8 NOT NULL,
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `email` varchar(255) CHARACTER SET utf8 NOT NULL,
  `sichtbarkeit_email` tinyint(1) NOT NULL DEFAULT 0,
  `titel` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `vorname` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `nachname` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `geschlecht` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'u',
  sichtbarkeit_geschlecht tinyint(1) NOT NULL DEFAULT 0,
  `geburtstag` date DEFAULT NULL,
  `aufnahmedatum` date DEFAULT NULL,
  `sichtbarkeit_geburtstag` tinyint(1) NOT NULL DEFAULT 1,
  `profilbild` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `profilbild_x` int(5) UNSIGNED NOT NULL DEFAULT 0,
  `profilbild_y` int(5) UNSIGNED NOT NULL DEFAULT 0,
  `mensa_nr` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_mensa_nr` tinyint(1) NOT NULL DEFAULT 1,
  `strasse` varchar(511) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_strasse` tinyint(1) NOT NULL DEFAULT FALSE,
  `adresszusatz` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_adresszusatz` tinyint(1) NOT NULL DEFAULT 0,
  `plz` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ort` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_plz_ort` tinyint(1) NOT NULL DEFAULT 0,
  `land` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_land` tinyint(1) NOT NULL DEFAULT 0,
  `strasse2` varchar(511) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `adresszusatz2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `plz2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ort2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `land2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `telefon` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_telefon` tinyint(1) NOT NULL DEFAULT 0,
  `mobil` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_mobil` tinyint(1) NOT NULL DEFAULT 0,
  `homepage` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sprachen` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `hobbys` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `interessen` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `beschaeftigung` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_beschaeftigung` tinyint(1) NOT NULL DEFAULT 1,
  `studienort` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_studienort` tinyint(1) NOT NULL DEFAULT 1,
  `studienfach` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_studienfach` tinyint(1) NOT NULL DEFAULT 1,
  `unityp` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_unityp` tinyint(1) NOT NULL DEFAULT 1,
  `schwerpunkt` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_schwerpunkt` tinyint(1) NOT NULL DEFAULT 1,
  `nebenfach` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_nebenfach` tinyint(1) NOT NULL DEFAULT 1,
  `abschluss` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_abschluss` tinyint(1) NOT NULL DEFAULT 1,
  `zweitstudium` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_zweitstudium` tinyint(1) NOT NULL DEFAULT 1,
  `hochschulaktivitaeten` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_hochschulaktivitaeten` tinyint(1) NOT NULL DEFAULT 1,
  `stipendien` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_stipendien` tinyint(1) NOT NULL DEFAULT 1,
  `auslandsaufenthalte` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_auslandsaufenthalte` tinyint(1) NOT NULL DEFAULT 1,
  `praktika` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_praktika` tinyint(1) NOT NULL DEFAULT 1,
  `beruf` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sichtbarkeit_beruf` tinyint(1) NOT NULL DEFAULT 1,
  `auskunft_studiengang` tinyint(1) NOT NULL DEFAULT 0,
  `auskunft_stipendien` tinyint(1) NOT NULL DEFAULT 0,
  `auskunft_auslandsaufenthalte` tinyint(1) NOT NULL DEFAULT 0,
  `auskunft_praktika` tinyint(1) NOT NULL DEFAULT 0,
  `auskunft_beruf` tinyint(1) NOT NULL DEFAULT 0,
  `mentoring` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_ma` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_orte` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_vortrag` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_koord` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_graphisch` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_computer` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_texte_schreiben` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_texte_lesen` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_vermittlung` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_ansprechpartner` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_hilfe` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_sonstiges` tinyint(1) NOT NULL DEFAULT 0,
  `aufgabe_sonstiges_beschreibung` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `db_modified` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `aktiviert` tinyint(1) NOT NULL DEFAULT '0',
   db_modified_user_id int UNSIGNED DEFAULT NULL,
   kenntnisnahme_datenverarbeitung_aufnahme datetime DEFAULT NULL,
   kenntnisnahme_datenverarbeitung_aufnahme_text text NOT NULL,
   einwilligung_datenverarbeitung_aufnahme datetime DEFAULT NULL,
   einwilligung_datenverarbeitung_aufnahme_text text NOT NULL,
   kenntnisnahme_datenverarbeitung datetime DEFAULT NULL,
   kenntnisnahme_datenverarbeitung_text text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci PACK_KEYS=0;

ALTER TABLE `mitglieder`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

ALTER TABLE `mitglieder`
  MODIFY `id` int(5) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

CREATE TABLE userdata_changelog (
    id int(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    userId int(5) UNSIGNED NOT NULL,
    changerUserId int(5) UNSIGNED NOT NULL DEFAULT 0,
    dataTimestamp datetime NOT NULL DEFAULT NOW(),
    dataName varchar(255) NOT NULL,
    oldValue text NOT NULL,
    newValue text NOT NULL,
    info text DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci PACK_KEYS=0;

CREATE TABLE deleted_usernames (
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` varchar(255) CHARACTER SET utf8 NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci PACK_KEYS=0;
