version: "3.5"
services:
  mitglieder:
    volumes:
      - "./app:/var/www"
      - "./update.d:/update.d"
      - "${VOLUMES_DIR}/profilbilder:/var/www/html/profilbilder"

  mitglieder-adminer:
    image: adminer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.mitglieder-adminer.entrypoints=websecure
      - traefik.http.routers.mitglieder-adminer.rule=Host(`mitglieder-adminer.${DOMAINNAME}`)
      - traefik.http.routers.mitglieder-adminer.middlewares=secheader@file
    depends_on:
      - mitglieder-database
    networks:
      - traefik
      - mitglieder
